/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package controller;

import java.io.IOException;
import java.io.InputStream;
import java.time.Duration;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import model.entities.ParkingLot;
import model.entities.User;
import model.entities.Vehicle;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

/**
 *
 * @author emman
 */
public class ReportService {

    public static String generateDailyReport(ParkingLot parkingLot, User user) throws IOException {

        if (parkingLot.getReportedVehicles().isEmpty()) {
            return null;
        }

        PDDocument document = new PDDocument();
        PDPage page = new PDPage();
        document.addPage(page);

        PDPageContentStream content = new PDPageContentStream(document, page);

        InputStream is = ReportService.class.getResourceAsStream("/imagenPark.png");
        if (is != null) {
            PDImageXObject logo = PDImageXObject.createFromByteArray(
                    document,
                    is.readAllBytes(),
                    "logo"
            );
            content.drawImage(logo, 50, 700, 200, 80);
        }

        content.beginText();
        content.setFont(PDType1Font.HELVETICA_BOLD, 14);
        content.setLeading(18f);
        content.newLineAtOffset(50, 660);

        LocalDateTime now = LocalDateTime.now();

        content.showText("DAILY PARKING REPORT");
        content.newLine();
        content.showText("Parking: " + parkingLot.getName());
        content.newLine();
        content.showText("Generated by: " + user.getName());
        content.newLine();
        content.showText("Date: " + now.toString());
        content.newLine();
        content.newLine();

        double totalIncome = 0;

        content.setFont(PDType1Font.HELVETICA, 12);
        content.showText("Vehicle registration of the day:");
        content.newLine();
        content.newLine();

        for (Vehicle v : parkingLot.getReportedVehicles()) {

            long minutes = Duration
                    .between(v.getEntryTime(), v.getExitTime())
                    .toMinutes();

            if (minutes <= 0) {
                minutes = 1;
            }

            double payment = minutes * v.getVehicleType().getFee();
            totalIncome += payment;

            content.showText(
                    "Plate: " + v.getPlate()
                    + " | Entry: " + v.getEntryTime()
                    + " | Exit: " + v.getExitTime()
                    + " | Fee: " + payment
            );

            content.newLine();
        }

        content.newLine();
        content.setFont(PDType1Font.HELVETICA_BOLD, 13);
        content.showText("TOTAL INCOME: " + totalIncome);

        content.endText();
        content.close();

        String fileName = "report_" + now.toString().replace(":", "-") + ".pdf";

        document.save(fileName);
        document.close();

        parkingLot.getReportedVehicles().clear();

        return fileName;
    }

}
